activation_dropout: 0.1
activation_fn: relu
adam_betas: 
- 0.9
- 0.98
adam_eps: 1.0e-08
adaptive_input: false
adaptive_softmax_cutoff: null
adaptive_softmax_dropout: 0
all_gather_list_size: 16384
arch: xtransformer
attention_dropout: 0.1
attn_loss_weight: 1.0
batch_size: null
batch_size_valid: null
best_checkpoint_metric: loss
bf16: false
bpe: null
broadcast_buffers: false
bucket_cap_mb: 25
checkpoint_path: /home/yi/Documents/projects/songmass/ckpts/songmass.pth
checkpoint_shard_count: 1
checkpoint_suffix: ''
clip_norm: 0.0
cpu: false
criterion: label_smoothed_cross_entropy_with_align
cross_self_attention: false
curriculum: 0
data: /home/yi/Documents/projects/songmass/lmd_data/processed
data_buffer_size: 10
dataset_impl: null
ddp_backend: c10d
decoder_attention_heads: 8
decoder_embed_dim: 512
decoder_embed_path: null
decoder_ffn_embed_dim: 2048
decoder_input_dim: 512
decoder_layerdrop: 0
decoder_layers: 6
decoder_layers_to_keep: null
decoder_learned_pos: false
decoder_normalize_before: false
decoder_output_dim: 512
device_id: 0
disable_validation: false
distributed_backend: nccl
distributed_init_method: null
distributed_no_spawn: false
distributed_num_procs: 0
distributed_port: -1
distributed_rank: 0
distributed_world_size: 1
distributed_wrapper: DDP
dropout: 0.1
empty_cache_freq: 0
encoder_attention_heads: 8
encoder_embed_dim: 512
encoder_embed_path: null
encoder_ffn_embed_dim: 2048
encoder_layerdrop: 0
encoder_layers: 6
encoder_layers_to_keep: null
encoder_learned_pos: false
encoder_normalize_before: false
eval_lang_pair: melody-lyric
eval_para: true
fast_stat_sync: false
find_unused_parameters: false
finetune_from_model: null
fix_batches_to_gpus: false
fixed_validation_seed: null
fp16: false
fp16_init_scale: 128
fp16_no_flatten_grads: false
fp16_scale_tolerance: 0.0
fp16_scale_window: null
gen_subset: test
ids_lang:
  0: lyric
  1: melody
keep_best_checkpoints: -1
keep_interval_updates: -1
keep_last_epochs: -1
label_smoothing: 0.0
langs:
- lyric
- melody
langs_id:
  lyric: 0
  melody: 1
layernorm_embedding: false
lazy_load: false
left_pad_source: true
left_pad_target: false
lm_bias: false
localsgd_frequency: 3
log_format: null
log_interval: 100
lr:
- 5.0e-05
lr_scheduler: inverse_sqrt
mass_steps:
- lyric-lyric
- melody-melody
max_epoch: 20
max_source_positions: 1024
max_target_positions: 1024
max_tokens: 4096
max_tokens_valid: 4096
max_update: 2000000
maximize_best_checkpoint_metric: false
memory_efficient_bf16: false
memory_efficient_fp16: false
min_loss_scale: 0.0001
min_lr: 1.0e-09
model_parallel_size: 1
mono_lang_pairs:
- lyric-lyric
- melody-melody
mt_steps:
- lyric-melody
- melody-lyric
n_lang: 2
no_cross_attention: false
no_epoch_checkpoints: true
no_last_checkpoints: false
no_progress_bar: false
no_save: false
no_save_optimizer_state: false
no_scale_embedding: false
no_seed_provided: false
no_token_positional_embeddings: false
nprocs_per_node: 1
num_shards: 1
num_workers: 1
optimizer: adam
optimizer_overrides: '{}'
para_lang_pairs:
- lyric-melody
patience: -1
pipeline_balance: null
pipeline_checkpoint: never
pipeline_chunks: 0
pipeline_decoder_balance: null
pipeline_decoder_devices: null
pipeline_devices: null
pipeline_encoder_balance: null
pipeline_encoder_devices: null
pipeline_model_parallel: false
pred_probs:
- 0.8
- 0.1
- 0.1
profile: false
quant_noise_pq: 0
quant_noise_pq_block_size: 8
quant_noise_scalar: 0
quantization_config_path: null
raw_text: false
reload_checkpoint: null
required_batch_size_multiple: 8
required_seq_len_multiple: 1
reset_dataloader: false
reset_lr_scheduler: false
reset_meters: false
reset_optimizer: false
restore_file: checkpoint_last.pt
save_dir: checkpoints
save_interval: 1
save_interval_updates: 0
scoring: bleu
seed: 1
sentence_avg: false
shard_id: 0
share_all_embeddings: false
share_decoder_input_output_embed: true
skip_invalid_size_inputs_valid_test: true
slowmo_algorithm: LocalSGD
slowmo_momentum: null
source_lang: null
source_langs:
- lyric
- melody
stop_time_hours: 0
target_lang: null
target_langs:
- lyric
- melody
task: xmasked_seq2seq
tensorboard_logdir: null
threshold_loss_scale: null
tie_adaptive_weights: false
tokenizer: null
tpu: false
training: true
train_subset: train
update_freq:
- 1
use_bmuf: false
use_old_adam: false
user_dir: /home/yi/Documents/projects/debug/muzic/songmass/mass
valid_lang_pairs:
- lyric-lyric
- melody-melody
valid_subset: valid
validate_after_updates: 0
validate_interval: 1
validate_interval_updates: 0
warmup_init_lr: 1.0e-07
warmup_updates: 4000
weight_decay: 0.0
word_mask: 0.25
word_mask_keep_rand: 0.8,0.1,0.1
zero_sharding: none
