checkpoint_path: /home/yi/Documents/projects/music-unlearn/ckpts/songmass.pth
activation_dropout: 0.1
attention_dropout: 0.1
data: /home/yi/Documents/projects/music-unlearn/lmd_data/processed
dropout: 0.1
decoder_embed_dim: 512
decoder_output_dim: 512
decoder_ffn_embed_dim: 2048
decoder_layers: 6
encoder_layers: 6
encoder_layerdrop: 0
encoder_embed_dim: 512
source_langs:
- lyric
- melody
share_all_embeddings: false
encoder_attention_heads: 8
decoder_attention_heads: 8
encoder_ffn_embed_dim: 2048
target_langs:
- lyric
- melody
langs:
- lyric
- melody
langs_id:
  lyric: 0
  melody: 1
max_source_positions: 1024
max_target_positions: 1024
mass_steps:
- lyric-lyric
- melody-melody
mt_steps:
- lyric-melody
- melody-lyric
mono_lang_pairs:
- lyric-lyric
- melody-melody
para_lang_pairs:
- lyric-melody
word_mask: 0.25
pred_probs:
- 0.8
- 0.1
- 0.1
